steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
       echo hello world
       echo hello world 2
  
  - name: gcr.io/cloud-builders/npm
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run test
